version: '3.1'
services:
  web:
    build: .
    depends_on:
      - db

  myapp:
    image: myapp_image 
    environment:
      SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:example@db/flask'
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env



  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIA_DATABASE: flask

  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:5000
